import type { PropsWithChildren } from 'react';
import type { Metadata } from 'next';
import { ClerkProvider } from '@clerk/nextjs';
import { Inter } from 'next/font/google';

import '@/styles/index.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: PropsWithChildren) => (
  <ClerkProvider>
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  </ClerkProvider>
);

export default RootLayout;
